consumes:
- application/json
info:
    description: HTTP server in Go with swagger endpoints definition.
    title: go-rest-api
    version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"

paths:
    /healthz:
        get:
            operationId: checkHealth
            produces:
            - text/plain
            responses:
                '200':
                    description: OK message
                    schema:
                        type: string
                        enum:
                        - OK

    /hello/{user}:
        get:
            description: Returns a welcome message to the user
            parameters:
                - name: user
                  in: path
                  type: string
                  required: true
                  description: the name of the user to welcome
            responses:
                200:
                    description: Returns the welcome message
                    schema:
                        type: string
                400:
                    description: Invalid characters in "user" were provided


    /gopher/{name}:
        get:
            description: Returns the gopher image
            produces:
            - image/png
            parameters:
                - name: name
                  in: path
                  type: string
                  required: true
                  description: The name of the gopher to display
            responses:
                200:
                    description: Returns the gopher
                    schema:
                        type: file